Repository basementdevs/scylla-studio, pull requests merged in 2024-10, with the labels that each got.

#10 feat(query-runner): display tracing information
  package.json
  pnpm-lock.yaml
  src/actions/execute-query.ts
  src/app/(main)/components/sidebar.tsx
  src/app/(main)/query-runner/_components/cql-editor.tsx
  src/app/(main)/query-runner/_components/results-render.tsx
  src/app/(main)/query-runner/_components/tracing-render.tsx
  src/components/ui/popover.tsx
  src/providers/index.tsx
Labels: enhancement

#13 feat(query-runner): display dashboard rendering
  src/app/(main)/query-runner/_components/cql-editor.tsx
  src/app/(main)/query-runner/_components/tracing-dashboard-render.tsx
Labels: enhancement

#22 chore: add connection port and add auth into query-runner
  src/actions/execute-query.ts
  src/app/(main)/components/command.tsx
  src/app/(main)/connections/_components/connection-table.tsx
  src/app/(main)/connections/_components/modal.tsx
  src/app/(main)/connections/actions/connections.ts
  src/lib/internal-db/connections.ts
  src/lib/menu-list.ts
Labels: enhancement

#24 Add option to select connection
  src/actions/query-keyspaces.ts
  src/app/(main)/query-runner/_components/cql-editor.tsx
  src/components/composed/select-database.tsx
  src/components/composed/sidebar/menu.tsx
  src/contexts/layout.tsx
  src/lib/internal-db/connections.ts
  src/lib/menu-list.ts
Labels: hacktoberfest-accepted

#26 feat: initial draft of the Dockerfile alternative
  .dockerignore
  Dockerfile
  README.md
  compose.yml
  next.config.mjs
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/actions/execute-query.ts
  src/app/(main)/connections/_components/connection-table.tsx
  src/app/(main)/connections/_components/modal.tsx
  src/app/(main)/query-runner/_components/tracing-dashboard-render.tsx
  src/components/ui/label.tsx
  src/lib/internal-db/connections.ts
Labels: hacktoberfest-accepted

#27 feat: add gh workflow for building and pushing Docker image
  .github/workflows/docker-image.yml
  Dockerfile
Labels: hacktoberfest-accepted

#28 feat: connection status
  src/app/(main)/connections/_components/connection-table.tsx
  src/app/(main)/connections/_components/table-item.tsx
  src/app/(main)/connections/actions/connections.ts
  src/lib/internal-db/connections.ts
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#32 refactor: home layout and project cleanup
  package-lock.json
  package.json
  src/app/(main)/components/header.tsx
  src/app/(main)/components/keep.tsx
  src/app/(main)/components/sidebar.tsx
  src/app/(main)/page.tsx
  src/components/composed/command.tsx
  src/components/composed/sidebar/content-layout.tsx
  src/components/composed/sidebar/footer.tsx
  src/components/composed/sidebar/menu.tsx
  src/components/composed/sidebar/navbar.tsx
  src/components/composed/sidebar/user-nav.tsx
  src/lib/menu-list.ts
Labels: enhancement, hacktoberfest-accepted, refactor

#38 refactor: replaced layout context to zustand layout store
  src/app/(main)/connections/_components/modal.tsx
  src/app/(main)/keyspace/[keyspace]/page.tsx
  src/app/(main)/keyspace/[keyspace]/table/[table]/page.tsx
  src/app/(main)/layout.tsx
  src/components/composed/command.tsx
  src/components/composed/select-database.tsx
  src/contexts/layout.tsx
  src/hooks/layout.ts
  src/lib/menu-list.ts
Labels: good first issue, hacktoberfest-accepted, refactor

#45 Fix connection delete and change table actions UX
  src/actions/query-keyspaces.ts
  src/app/(main)/connections/_components/connection-table.tsx
  src/app/(main)/connections/_components/modal.tsx
  src/app/(main)/connections/_components/row-actions.tsx
  src/app/(main)/connections/_components/table-item.tsx
  src/app/(main)/query-runner/_components/cql-editor.tsx
  src/components/ui/skeleton.tsx
  src/contexts/layout.tsx
  src/hooks/use-connections.ts
  src/lib/internal-db/connections.ts
  src/lib/menu-list.ts
  src/lib/utils.ts
Labels: enhancement, hacktoberfest
